on: #event qui trigger l'actions
  push:
    branches: [main]

jobs: #listes des actions
    build_and_push:
        runs-on: ubuntu-latest #OS qui sera utilis√© pour run les actions
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v6.0.0

            - name: Login to DockerHub
              id: docker_login
              if: steps.checkout.outcome == 'success'
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_HUB_USER}}
                password: ${{secrets.DOCKER_HUB_PASSWORD}}


        

            